// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lwsvbapkipseuqolfpji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3c3ZiYXBraXBzZXVxb2xmcGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDU4NDEsImV4cCI6MjA2OTUyMTg0MX0.btG8V8FI8ZmF5vxMcwctR_8MrvJLp0xNST-mik0aiQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // storage: localStorage,
    // persistSession: true,
    // autoRefreshToken: true,
    persistSession: false,
    autoRefreshToken: false,
    storage: undefined
  }
});